routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/balance', 'UserController@getBalance')->name('getUserBalance');
Route::get('/user/recent-transactions', 'UserController@getRecentTransactions')->name('getRecentTransactions');
Route::get('/user/should-show-overdrawn-alert', 'UserController@shouldShowOverdrawnAlert')->name('shouldShowOverdrawnAlert');
Route::get('/user/should-show-excess-alert', 'UserController@shouldShowExcessAlert')->name('shouldShowExcessAlert');
Route::get('/account', 'AccountController@show')->name('account.show');
Route::post('/transaction/store', 'TransactionController@store')->name('storeTransaction');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Money;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getOverdraftAttribute(){
        // TODO: user settings
        return 25000;
    }
    public function getOverdraftInPoundsAttribute(){
        return Money::fromPence($this->overdraft)->inPoundsAndPence();
    }
    public function getExcessAlertAttribute(){
        // TODO: user settings
        return 400000;
    }
    public function getExcessAlertInPoundsAttribute(){
        return Money::fromPence($this->excess_alert)->inPoundsAndPence();
    }

    /*
     * All balances associated with this user
     */
    public function balances()
    {
        return $this->hasMany('App\Balance');
    }

    /*
     * Originally used to select the most recently-entered balance.
     * Now defunct, unless we remove the ability for users to enter transaction dates,
     * which we may do.
     */
    public function balance()
    {
        return $this->hasOne('App\Balance')->latest();
    }

    /*
     * This user's most "recent" balance value (actually their newest balance, which could be in the future...)
     * Recency as measured by the transaction_date, not created_at date
     * TODO: review this future-balance question.
     */
    public function getCurrentBalanceValueAttribute(){
        $most_recent_transaction = $this->transactions()
            ->orderBy('transaction_date', 'desc')
            ->orderBy('id', 'desc')
            ->first();

        if($most_recent_transaction !== null){
            $current_balance = $most_recent_transaction->balance->value;
        } else {
            $current_balance = 0;
        }
        return $current_balance;
    }

    /*
     * All transactions associated with this user.
     */
    public function transactions()
    {
        return $this->hasMany('App\Transaction');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

<script type="text/javascript">
    $(function(){
        getCurrentBalance();
        getRecentTransactions();
        tryOverdrawnAlert();
        tryExcessAlert();
    })
</script>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="alert alert-warning overdrawn" role="alert">
                You are overdrawn.
            </div>

            <div class="alert alert-warning excess" role="alert">
                You have in excess of &pound;{{ Request::user()->excess_alert_in_pounds }} in your account.
                Please consider arranging a call with one of our investment specialists.
            </div>

        </div>
    </div>
</div>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="card current-balance">
                <!--<div class="card-header">{{ Request::user()->name }}'s Dashboard</div>-->

                <div class="card-body">

                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="current_balance">
                                    Your current balance is
                                    <span class="current-balance-value">
                                        ...
                                    </span>
                                </span>
                            </div>
                            <div class="col-md-6">
                                <span class="current_overdraft">
                                    Your overdraft is &pound;{{ Request::user()->overdraft_in_pounds }}
                                </span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Submit a Deposit</div>
                <div class="card-body">
                    @include('forms.deposit-quick')
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Submit a Withdrawl</div>
                <div class="card-body">
                    @include('forms.withdraw-quick')
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="card recent-transactions">
                <div class="card-header">Recent Transactions</div>

                <div class="card-body">

                    <div class="recent-transactions-headers">
                        <span>type</span>
                        <span>value</span>
                        <span>reference</span>
                        <span>date</span>
                        <span>balance</span>
                    </div>

                    <ul class="recent-transactions-list">
                        <li class="template">
                            <span class="transaction_type"></span>
                            <span class="transaction_value"></span>
                            <span class="transaction_reference"></span>
                            <span class="transaction_date"></span>
                            <span class="transaction_balance"></span>
                        </li>
                    </ul>

                </div>
            </div>

        </div>
    </div>
</div>

@endsection